### ISSUE TITLE
Would be nice if state were enum

### ISSUE THREAD

**Issue by MarcelRobitaille** [vv9k/docker-api-rs#10]
Thank you so much for making this! It is just what I need.

It would be nice if the container state were an enum not a string.

**Comment by vv9k** [comment]
I pushed some changes that update the type used by the `ContainerInfo::state` and `ContainerSummary::state` field. It is a bit misleading that the struct is name `ContainerStatus` but the field is called `state` but that is how Docker calls it so I'd prefer to keep it that way.

**Comment by MarcelRobitaille** [comment]
Awesome! Thank you so much. When can I expect to see that in a release?

**Comment by vv9k** [comment]
The version `0.7.0` was just released two days ago, so lets give it a week or two before another release.

**Comment by MarcelRobitaille** [comment]
Sounds good. Thank you

**Comment by vv9k** [comment]
A new release is out in case you are still interested in using the changes :)

**Comment by MarcelRobitaille** [comment]
Thanks for letting me know :)
