### ISSUE TITLE
Is this a shiplift fork? Comparison with bollard?

### ISSUE THREAD

**Issue by akiradeveloper** [vv9k/docker-api-rs#15]
I am trying to use some docker library to write tests. There looks 3 choices in the crates.io: shiplift, bollard and docker-api.

I tried shiplift first because it is best starred but after all I noticed it is unmaintained.

Then look into this library now and notice the APIs are much similar to shiplift. Question 1: Is this a fork?

Question 2 is about comparison with the alternative bollard. What is the strong point of this library against bollard?

**Comment by vv9k** [comment]
> Then look into this library now and notice the APIs are much similar to shiplift. Question 1: Is this a fork?

Yes, this crate is a fork of shiplit as is noted in the [README](https://github.com/vv9k/docker-api-rs#notice).

> Question 2 is about comparison with the alternative bollard. What is the strong point of this library against bollard?

I haven't used bollard personally as I only discovered it after starting my work on this crate so I can't really compare it. Glancing over bollard repository it seems pretty active and maintained so there is definitely that factor to consider. I am pretty responsive and plan to maintain this crate but bollard definitely has a wider user base and the codebase may be more thoroughly tested and documented.

**Comment by akiradeveloper** [comment]
I see. Thank you.
