### ISSUE TITLE
`Containers::create` can not set container name

### ISSUE THREAD

**Issue by avalon1610** [vv9k/docker-api-rs#5]
- Crate version: 0.5.1
- OS: CentOS 7
- Output of running `docker version` on the command line:  
  - Version: 20.10.8
  - API version: 1.41

In docker api version 1.41, `/container/create` 's name argument should pass by **Query Parameters**
see https://docs.docker.com/engine/api/v1.41/#operation/ContainerCreate

**Comment by vv9k** [comment]
Welcome! Thanks for the report. After #6 gets merged it should be possible to do this:
 ```rust
 let opts = ContainerCreateOpts("image-name:latest")::builder().name("container-name").build();
 docker.containers().create(&opts).await;
 ```
