### ISSUE TITLE
Add `—net` option to container creation.

### ISSUE THREAD

**Issue by lorecast162** [vv9k/docker-api-rs#52]
Greetings,
After looking into source code, docs.rs documentation for this crate and code editor autocomplete I couldn’t find a way to connect a container to a network during creation (as with the `--network` flag).

Have I missed this  or is this actually not implemented yet?

**Comment by vv9k** [comment]
Thanks for the report! This flag was previously unavailable. I've added it in 69bade2 so it should be possible now.

**Comment by lorecast162** [comment]
Thank you for the response :D
I’ll get to trying this out as soon as I can
