### ISSUE TITLE
Stdin for Execs

### ISSUE THREAD

**Issue by lvrg-acc** [vv9k/docker-api-rs#53]
Hello, thank you for creating this library, enjoying it a lot.

But there's a problem I couldn't quite figure out how to solve:

Let's say I have a running container which I attached using `.attach()`, which streams some stdout, then I want to make a separate exec (docker exec -it <id> /bin/sh) to work with this container in a separate tab, but seems like I could't do it because `container.exec()` returns only output and doesn't have an option to accept input.

I'd like to propose adding the ability to use attach for execs, or provide stdin handle for execs.

I would like to hear your thoughts on this, thank you.

**Comment by vv9k** [comment]
Hello, thank you for this suggestion.

Somehow I think STDIN got overlooked in the initial implementation but I went ahead and made the necessary changes to be able to write to the stream returned by exec.

I've tested it locally on a minimal example where I upgraded ubuntu container using `apt upgrade` and I wrote to the returned multiplexer `y` character and it worked.

**Comment by lvrg-acc** [comment]
Thank you! Tested on my sample, works exactly as I wanted.
