### ISSUE TITLE
`Containers::inspect` is not working

### ISSUE THREAD

**Issue by avalon1610** [vv9k/docker-api-rs#7]
- Crate version: 0.5.1
- OS:  CentOS 7
- Output of running `docker version` on the command line:
  - Version: 20.10.8
  - API version: 1.41

the struct `ContainerInfo`'s layout seems not match to the [docker api](https://docs.docker.com/engine/api/v1.41/#operation/ContainerInspect)

**Comment by vv9k** [comment]
Sure thing.

**Comment by vv9k** [comment]
Should be up on crates.io .
